### ISSUE TITLE
Move the Read The Docs black bar back under menu list

### ISSUE THREAD

**Issue by AllenMcAfee** [Robo3D/support.robo3d.com#23]
@bkabili @CobyKabili Ben had moved the black bar I'm showing in the attached picture out from under the menu list, but on smaller screens is blocks out the links for the bottom of the lists as they expand.  

Can we move this back inline with the menu?

![screen shot 2017-04-19 at 5 34 36 pm](https://cloud.githubusercontent.com/assets/4200307/25207993/a99a2a62-2526-11e7-9af2-c244889689b7.png)

**Comment by bkabili** [comment]
@AllenMcAfee I added a larger margin to the bottom of the menu so that you can always scroll to the bottom of the menu even if you are on a small screen and the black bar is over the menu. You should be able to get to all parts of the menu no matter what. 
![screen shot 2017-04-20 at 1 48 13 pm](https://cloud.githubusercontent.com/assets/5116731/25249761/54ab509e-25d0-11e7-903d-045dd64bfbbd.png)
In the out of the box Read the Docs styling, the bar covers the menu as well and you can scroll to the bottom similar to how we have it set now. Would you rather have it a different way?
![screen shot 2017-04-20 at 1 48 44 pm](https://cloud.githubusercontent.com/assets/5116731/25249768/59e4926e-25d0-11e7-9088-2ab92122fada.png)

**Comment by bkabili** [comment]
@AllenMcAfee @CobyKabili can we close this or do we still want the bar moved?

**Comment by AllenMcAfee** [comment]
@bkabili It is still problematic in it's current state.  Check the photo below.
![screen shot 2017-06-12 at 2 02 48 pm](https://user-images.githubusercontent.com/4200307/27055028-e31e56b6-4f77-11e7-82de-7dcf99616ba6.png)

The bar still overs the text if the menu is long enough.  If we can move this directly under the menu, and shrink the menu's bottom margin to fit it, then I think we're in business.
